### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by alex-bender** [catvmzhang/UNIXCourses_SimpleInstructionLevel_Debugger#1]
Hi there!
There are a lot of interesting repositories. I see that they are named after some
`UNIXCoutses`. Could you please share the course itself? Looks very promising.
Thanks for sharing.

**Comment by catvmzhang** [comment]
The course is called "Advanced Programming in the UNIX Environment" in
NCTU, TW, but  sorry for that it doesn't have the video online.
So, if you are interested in the courses, you can refer to W. Richard
Stevens and Stephen A. Rago, "Advanced Programming in the UNIX Environment,"
2nd ed. or 3rd ed., Addison Wesley.

Regards.

Alex Bender <notifications@github.com> 於 2019年7月29日 週一 下午11:37寫道：

**Comment by alex-bender** [comment]
Thanks a lot for your reply!
